// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDZExaEL0XKDD1St_9w-JgPIbXi0j8Rto',
    appId: '1:203695116201:web:9996dfc5c05bda2a907eb8',
    messagingSenderId: '203695116201',
    projectId: 'home-renting-system',
    authDomain: 'home-renting-system.firebaseapp.com',
    storageBucket: 'home-renting-system.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAG7Rm314zpldJCKl5OOt5qcwKM4NxQOU',
    appId: '1:203695116201:android:3de05062a1c51ab3907eb8',
    messagingSenderId: '203695116201',
    projectId: 'home-renting-system',
    storageBucket: 'home-renting-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzKqA-bsRw8CyXg0QmfSKrZA8GyiTAIgI',
    appId: '1:203695116201:ios:f677feef277c9df5907eb8',
    messagingSenderId: '203695116201',
    projectId: 'home-renting-system',
    storageBucket: 'home-renting-system.firebasestorage.app',
    iosBundleId: 'com.example.homeRentingSystem',
  );

}